version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Collabora-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # <--- empêche l'écrasement par node_modules local
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/collabora_db

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
